### ISSUE TITLE
package javax.xml.bind is declared in module java.xml.bind, which is not in the module graph | Cooja Ant Build

### ISSUE THREAD

**Issue by kaleemullah360** [contiki-os/contiki#2214]
Latest clone causes trouble, please help. not interested in stable release

```
Buildfile: contiki/tools/cooja/build.xml

init:

compile:
    [javac] Compiling 170 source files to contiki/tools/cooja/build
    [javac] /contiki/tools/cooja/java/org/contikios/cooja/contikimote/interfaces/ContikiEEPROM.java:41: error: package javax.xml.bind is not visible
    [javac] import javax.xml.bind.DatatypeConverter;
    [javac]                 ^
    [javac]   (package javax.xml.bind is declared in module java.xml.bind, which is not in the module graph)
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error

BUILD FAILED
/home/ku/kontiki/tools/cooja/build.xml:77: Compile failed; see the compiler error output for details.

Total time: 7 seconds
```

**Comment by kaleemullah360** [comment]
update JDK, JRE, solved the issue. thanks. closing it.

**Comment by hexiaole1994** [comment]
Hello,man
I have the same problem with yours
and I'm using jdk-9 which seems the newest version of jdk 
but still has problem,what should I do?
please help me

**Comment by kilgore92** [comment]
This is an [issue with jdk-9](https://stackoverflow.com/questions/46084302/package-javax-xml-soap-is-declared-in-module-java-xml-ws-which-is-not-in-the-m). Install jdk-8 and set it to default. Should fix the problem.

**Comment by hexiaole1994** [comment]
@kilgore92 Thank you,that will fix my issue 
and I wonder if it can be fixed at jdk-9
:0

**Comment by Jean-Baptiste-B** [comment]
deprecated in JDK9 deprecated for removal, use JDK8 instead

**Comment by JihenHlel** [comment]
@kaleemullah360  i had the same problem while runing ant, i updated jdk and jre but still the same error :( can you please give me the command line which you used for updating the jdk !

**Comment by souhilahana** [comment]
@JihenHlel i have  the same problem!!!!

**Comment by JihenHlel** [comment]
@souhilahana  already a week i posted my problem in multiples sites and forums but i didn't get any response :(

**Comment by souhilahana** [comment]
I'm also, if you find a solution tell me please

--

Souhila Kettouche,

PhD student at Relacs Laboratory,

Oum Bouagui University

1er Novembre 1954, Oum el Bouaghi 04000, Algérie

+213.6.97.38.71.35

**Comment by Sambalinski** [comment]
https://www.logicbig.com/tutorials/core-java-tutorial/modules/root-modules.html

**Comment by Vinggui** [comment]
Well, I think that using an old version of java is **not** the best solution.
Honestly, I'm not very experienced with ant and java, so I can not give a complete answer now.
### Immediate solution
Considering that you have ubuntu 16.04+ and installed all the necessary packages:
```
sudo apt-get install build-essential binutils-msp430 gcc-msp430 msp430-libc msp430mcu mspdebug gcc-arm-none-eabi openjdk-8-jdk openjdk-8-jre ant libncurses5-dev lib32ncurses5
```

Solving this problem is just:
```
sudo update-alternatives --config java
```
select the old java version (java-8-openjdk, probably option *2*)

### Better future solution
If someone else wants to solve this problem once and for all, a good start is in the build.xml file inside "tools/cooja".
Adding the following line made Cooja start and simulate:
`<compilerarg line="--add-modules java.xml.bind"/>`

Hence, the final compile command would be:
```
<target name="compile" depends="init">
    <mkdir dir="${build}"/>
    <javac srcdir="${java}" destdir="${build}" debug="on"
           includeantruntime="false"
           encoding="utf-8">
      <compilerarg line="--add-modules java.xml.bind"/>
      <classpath>
        <pathelement path="."/>
        <pathelement location="lib/jdom.jar"/>
        <pathelement location="lib/log4j.jar"/>
        <pathelement location="lib/jsyntaxpane.jar"/>
        <pathelement location="lib/swingx-all-1.6.4.jar"/>
      </classpath>
    </javac>
  </target>
```
However, some errors were shown, which did not stop simulation from working, so I don't know its impact.

**Machine tested:**
*Ubuntu 18.04 64bits
*java11(default) and java8 installed

**Comment by souhilahana** [comment]
The Problem is solved thenkyouuuuuuu so much.
--

Souhila



Le mar. 7 août 2018 23:07, Vinicius Guimaraes <notifications@github.com> a
écrit :

**Comment by gptshubham595** [comment]
I am using jdk 11

added it in as path in .bashrc
 also added 
```<compilerarg line="--add-modules java.xml.bind"/>```
But it says module not found

![image](https://user-images.githubusercontent.com/24877361/97917190-204c0280-1d7a-11eb-9124-297f0e942b62.png)

**Comment by Vinggui** [comment]
@gptshubham595 I don't remember seeing this error. Also, you are using Contiki-ng. I don't know what changed in this way. Nevertheless, I'll suggest these steps to find the problem:
- Verify your Java installation and option with `sudo update-alternatives --config java`;
- Check if you installed the submodules correctly `git submodule update --init --recursive.`
Good luck. Please report back if you find the solution.

**Comment by gururaj1711** [comment]
> sudo update-alternatives --config java

Thank you so much
